replicaCount: 2

image:
  repository: 730335572375.dkr.ecr.us-east-1.amazonaws.com/tf-k8s-three-prod/api
  tag: 32ba49786a89713fc7fab02f16281892f0e22b6e
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi

ingress:
  enabled: true

database:
  host: tf-k8s-three-prod-postgres.ck968c8q2md1.us-east-1.rds.amazonaws.com
  port: 5432
  name: appdb
  secretArn: arn:aws:secretsmanager:us-east-1:730335572375:secret:rds!db-fda799cd-dabc-4cf7-9700-23d27a37a75b-RbTYI
