replicaCount: 2

image:
  repository: 730335572375.dkr.ecr.us-east-1.amazonaws.com/tf-k8s-three-prod/api
  tag: 21925a4a368224318e5e89ac6c67f59ba61b9325
  pullPolicy: IfNotPresent

service:
  port: 80
  targetPort: 3000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    memory: 128Mi
